### ISSUE TITLE
doctl sls connect fails on snap

### ISSUE THREAD

**Issue by Carlgo11** [digitalocean/doctl#1171] opened 2022-05-26 01:30 UTC
**Describe the Issue:**

Using doctl sandbox connect results in a permission error.
```
$ doctl sandbox connect --trace
doctl: 2022/05/26 03:27:35 -> "POST /v2/functions/sandbox HTTP/1.1\r\nHost: api.digitalocean.com\r\nUser-Agent: doctl/1.76.0-release (linux amd64) godo/1.80.0\r\nContent-Length: 0\r\nAccept: application/json\r\nContent-Type: application/json\r\nAccept-Encoding: gzip\r\n\r\n"
doctl: 2022/05/26 03:27:36 <- "HTTP/2.0 200 OK\r\nCache-Control: max-age=0, private, must-revalidate\r\nCf-Cache-Status: DYNAMIC\r\nCf-Ray: 7112baae2c324c07-AMS\r\nContent-Type: application/json; charset=utf-8\r\nDate: Thu, 26 May 2022 01:27:35 GMT\r\nExpect-Ct: max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\"\r\nRatelimit-Limit: 5000\r\nRatelimit-Remaining: 4985\r\nRatelimit-Reset: 1653529777\r\nServer: cloudflare\r\nSet-Cookie: __cf_bm=2RhuatRG.YJXco8oNslyOW7_wUdlXYdNjIElKVlb6hg-1653528455-0-AQvqzlHtnlpSpgKLiKa+arY6LH6c8GEMR6Plb3VcfE96sqNolTEplbMJXaSxXUQxI0diumm8fIPCRYirM3Ky/52pnVAoLmHBConjwSXrZ7mB; path=/; expires=Thu, 26-May-22 01:57:35 GMT; domain=.digitalocean.com; HttpOnly; Secure; SameSite=None\r\nX-Gateway: Edge-Gateway\r\nX-Request-Id: 117a536c-db45-4f03-91e9-b22e10e480c6\r\nX-Response-From: portal-aggregator\r\n\r\n{\"namespace\":{\"api_host\":\"https://faas-nyc1-2ef2e6cc.doserverless.co\",\"namespace\":\"fn-e2a85d8c-5ea8-4909-8236-03b8f7e07e22\",\"created_at\":null,\"updated_at\":null,\"label\":\"\",\"region\":\"nyc1\",\"tags_json\":null,\"uuid\":\"51a35987-4c12-4220-84e2-86a4671bc1d2\",\"key\":\"B58fgjw6uz0AWHNzAN2e5EPDR2p7XnFG6mpLGTgOUprf4gTA9ufX6JSfuIs9scIN\"}}\n"
Error: fork/exec /home/carlgo11/.config/doctl/sandbox/node: permission denied
```

**Environment:**

 - doctl version:
   ```
   doctl version 1.76.0-release
   Git commit hash: edfd9c50
   ```
 - OS: Ubuntu 21.04 LTS
 - Installation method: Snap 2.55.5

**Additional Details:**
I have enabled all available snap permission (snap connect) to doctl and tried setting the permissions of `$HOME/.config/doctl` to 777 but nothing worked.
Snap connections are as follows:
```
$ snap connections | grep doctl
home                                            doctl:home                               :home                                                                     -
network                                         doctl:network                            :network                                                                  -
personal-files                                  doctl:doctl-config                       :personal-files                                                           -
personal-files                                  doctl:dot-docker                         :personal-files                                                           manual
personal-files                                  doctl:kube-config                        :personal-files                                                           manual
ssh-keys                                        doctl:ssh-keys                           :ssh-keys                                                                 manual
```

**Comment by rabbah** [comment] 2022-05-26 01:52
Thanks @Carlgo11 for the bug report. Try this workaround. You may have to adapt the first part of the `mv` to match your path.

```
mv /tmp/doctl-sandbox*/node-v16.13.0-linux-x64/ ~/.config/doctl/sandbox/nodejs
ln -s $HOME/.config/doctl/sandbox/nodejs/bin/node $HOME/.config/doctl/sandbox/nodejs/bin/node        
```

**Comment by joshuaauerbachwatson** [comment] 2022-05-26 13:03
The workaround suggested above by @rabbah is inapplicable ... it was a workaround for a different bug, since fixed.

The problem here is with `snap`.   I have been able to reproduce the problem.   The install step succeeds completely and a subsequent check shows that all the components have installed correctly.   For example, if I explicitly type `/home/.../.config/doctl/sandbox/node` at a terminal prompt, it executes just fine.   But, I believe the confined environment that `doctl` is running in when installed by `snap` simply does not permit executing binaries outside the confined area.   I also looked at all the `snap` permissions and didn't see one that would affect executing binaries.   Most of the `doctl sandbox` commands require this.

I also tried uninstalling and reinstalling with the `--classic` flag.   Supposedly, this allows the binary to be installed in an "unconfined" way.   But, this capability has to be enabled by the packager (that's us, at DigitalOcean) and I have not yet had a chance to explore whether this is an option.

I think the immediate bottom line is
- the sandbox commands will not work with a `snap` install of `doctl`.    Doing a direct download from the release site https://github.com/digitalocean/doctl/releases is the only current path for linux users
- this is our bad: our testing covered only the direct download cases (lesson learned)
- I don't know of a workaround but hope others might
- meanwhile, we'll work to fix this transparently (if possible) or at least support `--classic` installs.

**Comment by joshuaauerbachwatson** [comment] 2022-05-26 17:06
There is actually a workaround while continuing to use `snap` to install.
```
snap remove doctl
snap install doctl --devmode
```
Starting with point release 1.76.1, `doctl sandbox install` will detect that it is running in a Snap and will make this suggestion.

We're thinking about a better fix, but we can't give a timetable yet.

**Comment by andrewsomething** [comment] 2022-05-26 23:15
We've just release version 1.76.2 which should resolve this issue and allow for the `doctl sandbox` commands to work as expected without needing to use `--devmode`.  To upgrade to the new release, run:

    sudo snap refresh doctl

This is accomplished by shipping the sandbox environment along side `doctl` in the Snap package. Now when installed as a Snap, you will no longer need to run `doctl sandbox install` and can proceed directly to calling `doctl sandbox connect`

Thanks again for flagging this for us, and let us know if you run into any other issues.

Closed via https://github.com/digitalocean/doctl/pull/1173

**Closed by andrewsomething** 2022-05-26 23:15 UTC
Labels: bug
