### ISSUE TITLE
go get not working

### ISSUE THREAD

**Issue by atomi** [digitalocean/doctl#147] opened 2016-10-03 16:03 UTC
```
$ go get github.com/digitalocean/doctl/cmd/doctl
# cd /opt/go/src/github.com/digitalocean/doctl; git submodule update --init --recursive
fatal: no submodule mapping found in .gitmodules for path 'vendor/github.com/vektra/errors'
package github.com/digitalocean/doctl/cmd/doctl: exit status 128
```

**Comment by xmudrii** [comment] 2016-10-03 16:06
Could be duplicate of #42.
If you execute `go get github.com/digitalocean/doctl/cmd/doctl` again, it should install Doctl for you. For me usually it fails first time, but second time it works normally.

**Closed** 2017-04-04 18:42 UTC
