### ISSUE TITLE
"doctl compute droplet untag" - droplet not found bug

### ISSUE THREAD

**Issue by snoopdouglas** [digitalocean/doctl#119] opened 2016-07-26 16:47 UTC
I'm trying to remove a tag from a droplet, and so far have tried all the following commands:

```
doctl compute droplet untag dropletname tagname
doctl compute droplet untag tagname dropletname
doctl compute droplet untag tagname --droplet-name dropletname
```

Each one gives these errors respectively:

```
Error: (droplet.untag) command is missing required arguments
Error: (droplet.untag) command is missing required arguments
Error: droplet with name "[dropletname]" could not be found
```

Am I doing something wrong or is this a bug? The droplet and tag definitely exist.

In addition, the usage statement for this is rather unclear:
```
Usage:
  doctl compute droplet untag <droplet id or name> [flags]

Flags:
      --droplet-name value   Droplet names (default [])
```

Version: 1.3.1

**Comment by bryanl** [comment] 2016-07-26 16:50
Confirmed, this is a bug.

**Comment by bryanl** [comment] 2016-07-26 16:50
It looks like we are shaping up to do a release hopefully by the end of the week. I expect a fix in master earlier than that, however.

**Comment by bryanl** [comment] 2016-07-26 17:07
As for the statement, I agree, `doctl compute droplet untag <tagname> --droplet-name` is backwards.  Perhaps it should be `doctl compute droplet untag <droplet names or ids> --tag-name <foo> --tag-name <bar>`

**Comment by snoopdouglas** [comment] 2016-07-26 17:41
This'd indeed be good IMO:

`doctl compute droplet untag <droplet names or ids> --tag-name <foo> --tag-name <bar>`

...because then it matches the syntax of `compute droplet tag`. :)

**Comment by snoopdouglas** [comment] 2016-08-03 13:41
@bryanl do you reckon this will be merged before 1.4.1?

**Comment by bryanl** [comment] 2016-08-03 13:51
Yes, it'll be merged today or tomorrow. And I think we'll do a 1.4.1 early next week.

**Comment by snoopdouglas** [comment] 2016-08-03 14:32
Excellent, cheers.

**Closed** 2016-08-04 14:10 UTC
Labels: bug
